food = ["黒糖"]
food = ["ゴーヤチャンプルー"]
food = ["沖縄そば"]
food = ["ラフテー"]
food = ["ステーキ"]
food = ["ポークたまごおにぎり"]
food = ["島豆腐"]
food = ["ジーマミー豆腐"]
food = ["豆腐よう"]
food = ["沖縄おでん"]
food = ["沖縄天ぷら"]
food = ["海ぶどう"]
food = ["アグー豚"]
food = ["ミミガー"]
food = ["アンダンスー"]
food = ["テビチ"]
food = ["島らっきょう"]
food = ["パパイヤ"]
food = ["イーチョーバー"]
food = ["カンダバー"]
food = ["サクナ"]
food = ["シカクマメ"]
food = ["ハンダマ"]
food = ["サーターアンダギー"]
food = ["ブルーシールアイスクリーム"]
food = ["ちんすこう"]
food = ["沖縄ぜんざい"]
food = ["パイナップル"]
food = ["マンゴー"]
food = ["オリオンビール"]
food = ["泡盛"]
food = ["さんぴん茶"]
